CREATE DATABASE BIBLIOTHEQUE
GO
USE BIBLIOTHEQUE
GO
CREATE TABLE livre(
   ID_LIVRE INT IDENTITY(1,1) NOT NULL,
   titre VARCHAR(255) NOT NULL,
   isbn VARCHAR(255) NOT NULL,
   deleted BIT NOT NULL,
   CONSTRAINT PK_LIVRE PRIMARY KEY NONCLUSTERED 
	(
		ID_LIVRE ASC
	)
)
GO

CREATE TABLE theme(
   ID_THEME INT IDENTITY(1,1) NOT NULL,
   titre VARCHAR(255),
   deleted BIT NOT NULL,
   CONSTRAINT PK_THEME PRIMARY KEY NONCLUSTERED 
	(
		ID_THEME ASC
	)
)
GO

CREATE TABLE motcle(
   ID_MOTCLE INT IDENTITY(1,1) NOT NULL,
   mot VARCHAR(255),
   deleted BIT NOT NULL,
    CONSTRAINT PK_MOTCLE PRIMARY KEY NONCLUSTERED 
	(
		ID_MOTCLE ASC
	)
)
GO

CREATE TABLE auteur(
   ID_AUTEUR INT IDENTITY(1,1) NOT NULL,
   nom VARCHAR(255),
   prenom VARCHAR(255),
   deleted BIT NOT NULL,
   CONSTRAINT PK_AUTEUR PRIMARY KEY NONCLUSTERED 
	(
		ID_AUTEUR ASC
	)

)
GO

CREATE TABLE editeur(
   ID_EDITEUR INT IDENTITY(1,1) NOT NULL,
   nom VARCHAR(255),
   deleted BIT NOT NULL,
   CONSTRAINT PK_EDITEUR PRIMARY KEY NONCLUSTERED 
	(
		ID_EDITEUR ASC
	)
)
GO

CREATE TABLE usure(
   ID_USURE INT IDENTITY(1,1) NOT NULL,
   etat VARCHAR(255),
   deleted BIT NOT NULL,
   CONSTRAINT PK_USURE PRIMARY KEY NONCLUSTERED 
	(
		ID_USURE ASC
	)
)
GO

CREATE TABLE categorie(
   ID_CATEGORIE INT IDENTITY(1,1) NOT NULL,
   titre VARCHAR(255),
   deleted BIT NOT NULL,
   CONSTRAINT PK_CATEGORIE PRIMARY KEY NONCLUSTERED 
	(
		ID_CATEGORIE ASC
	)
)
GO

CREATE TABLE exemplaire(
   ID_EXEMPLAIRE INT IDENTITY(1,1) NOT NULL,
   date_achat DATE,
   emplacement VARCHAR(255),
   deleted BIT NOT NULL,
   ID_EDITEUR INT NOT NULL,
   ID_USURE INT NOT NULL,
   ID_LIVRE INT NOT NULL,


   CONSTRAINT PK_EXEMPLAIRE PRIMARY KEY NONCLUSTERED 
	(
		ID_EXEMPLAIRE ASC
	),
   CONSTRAINT FK_EXEMPLAIRE_EDITEUR FOREIGN KEY(ID_EDITEUR) REFERENCES editeur(ID_EDITEUR),
   CONSTRAINT FK_EXEMPLAIRE_USURE FOREIGN KEY(ID_USURE) REFERENCES usure(ID_USURE),
   CONSTRAINT FK_EXEMPLAIRE_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES livre(ID_LIVRE)
)
GO

CREATE TABLE abonne(
   ID_ABONNE INT IDENTITY(1,1) NOT NULL,
   nom VARCHAR(255),
   prenom VARCHAR(255),
   adresse VARCHAR(255),
   date_adhesion DATE,
   matricule VARCHAR(255),
   telephone VARCHAR(255),
   date_naissance DATE,
   email VARCHAR(255),
   password VARCHAR(255),
   deleted BIT NOT NULL,

   ID_CATEGORIE INT NOT NULL,
   CONSTRAINT PK_ABONNE PRIMARY KEY NONCLUSTERED 
	(
		ID_ABONNE ASC
	),
   UNIQUE(email),
   CONSTRAINT FK_ABONNE_CATEGORIE FOREIGN KEY(ID_CATEGORIE) REFERENCES categorie(ID_CATEGORIE)
)
GO

CREATE TABLE reservation(
   ID_RESERVATION INT IDENTITY(1,1) NOT NULL,
   date_reservation DATE,
   deleted BIT NOT NULL,

   ID_EDITEUR INT NOT NULL,
   ID_LIVRE INT NOT NULL,
   ID_ABONNE INT NOT NULL,

   CONSTRAINT PK_RESERVATION PRIMARY KEY NONCLUSTERED 
	(
		ID_RESERVATION ASC
	),
   CONSTRAINT FK_RESERVATION_EDITEUR FOREIGN KEY(ID_EDITEUR) REFERENCES editeur(ID_EDITEUR),
   CONSTRAINT FK_RESERVATION_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES livre(ID_LIVRE),
   CONSTRAINT FK_RESERVATION_ABONNE FOREIGN KEY(ID_ABONNE) REFERENCES abonne(ID_ABONNE)
)
GO

CREATE TABLE emprunt(
   ID_EMPRUNT INT IDENTITY(1,1) NOT NULL,
   date_sortie DATE,
   date_retour DATE,
   deleted BIT NOT NULL,

   ID_EXEMPLAIRE INT NOT NULL,
   ID_ABONNE INT NOT NULL,

   CONSTRAINT PK_EMPRUNT PRIMARY KEY NONCLUSTERED 
	(
		ID_EMPRUNT ASC
	),
   CONSTRAINT FK_EMPRUNT_EXEMPLAIRE FOREIGN KEY(ID_EXEMPLAIRE) REFERENCES exemplaire(ID_EXEMPLAIRE),
   CONSTRAINT FK_EMPRUNT_ABONNE FOREIGN KEY(ID_ABONNE) REFERENCES abonne(ID_ABONNE)
)
GO

CREATE TABLE auteur_livre(
   ID_LIVRE INT,
   ID_AUTEUR INT,

   

   CONSTRAINT PK_AUTEUR_LIVRE PRIMARY KEY NONCLUSTERED 
	(
		ID_LIVRE ASC,
		ID_AUTEUR ASC
	),
   CONSTRAINT FK_AUTEUR_LIVRE_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES livre(ID_LIVRE),
   CONSTRAINT FK_AUTEUR_LIVRE_AUTEUR FOREIGN KEY(ID_AUTEUR) REFERENCES auteur(ID_AUTEUR)
)
GO

CREATE TABLE livre_motcle(
   ID_LIVRE INT,
   ID_MOTCLE INT,
   CONSTRAINT PK_LIVRE_MOTCLE PRIMARY KEY NONCLUSTERED 
	(
		ID_LIVRE ASC,
		ID_MOTCLE ASC
	),
   CONSTRAINT FK_LIVRE_MOTCLE_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES livre(ID_LIVRE),
   CONSTRAINT FK_LIVRE_MOTCLE_MOTCLE FOREIGN KEY(ID_MOTCLE) REFERENCES motcle(ID_MOTCLE)
)
GO

CREATE TABLE livre_theme(
   ID_LIVRE INT,
   ID_THEME INT,
   CONSTRAINT PK_LIVRE_THEME PRIMARY KEY NONCLUSTERED 
	(
		ID_LIVRE ASC,
		ID_THEME ASC
	),
   CONSTRAINT FK_LIVRE_THEME_LIVRE FOREIGN KEY(ID_LIVRE) REFERENCES livre(ID_LIVRE),
   CONSTRAINT FK_LIVRE_THEME_THEME FOREIGN KEY(ID_THEME) REFERENCES theme(ID_THEME)
)
GO
